[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
lib_deps =
    sparkfun/SparkFun Qwiic 6Dof - LSM6DSO@^1.0.3
    bblanchon/ArduinoJson@^7.4.2
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    madhephaestus/ESP32Servo@^3.0.9
    sandeepmistry/LoRa@^0.8.0
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit CAP1188 Library@^1.1.0
build_flags =
    -DCORE_DEBUG_LEVEL=1